global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'rigger-backend'
    static_configs:
      - targets: ['rigger-backend-local:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'riggerhub-web'
    static_configs:
      - targets: ['riggerhub-web-local:3000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'riggerconnect-web'
    static_configs:
      - targets: ['riggerconnect-web-local:3000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'postgres'
    static_configs:
      - targets: ['rigger-postgres-local:5432']
    scrape_interval: 30s

  - job_name: 'redis'
    static_configs:
      - targets: ['rigger-redis-local:6379']
    scrape_interval: 30s

  - job_name: 'mongodb'
    static_configs:
      - targets: ['rigger-mongodb-local:27017']
    scrape_interval: 30s
