name: RiggerConnectIOS
options:
  bundleIdPrefix: com.tiation
  deploymentTarget:
    iOS: '13.0'
targets:
  RiggerConnectIOS:
    type: application
    platform: iOS
    sources:
      - Sources
    resources:
      - Resources
    info:
      path: Info.plist
    settings:
      base:
        DEVELOPMENT_TEAM: 'DEVELOPMENT_TEAM'
        PRODUCT_BUNDLE_IDENTIFIER: com.tiation.riggerconnect
