// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ekerxpltgkxerpxsuowm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVrZXJ4cGx0Z2t4ZXJweHN1b3dtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4OTQxMTcsImV4cCI6MjA2ODQ3MDExN30.wFNVr53phxB2lQfu-3durvkPxduFtIBJwmIs99n0o8s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});