[build]
  publish = "out"
  command = "npm run build && npm run export"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "8"
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_ENV = "production"

# Next.js function handling
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Redirect rules for Next.js app router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://generativelanguage.googleapis.com https://vercel.live https://vitals.vercel-insights.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https: blob:; connect-src 'self' https://generativelanguage.googleapis.com https://api.supabase.co wss://*.supabase.co https://vitals.vercel-insights.com; frame-src 'self';"

# Cache optimization
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment variables (add your actual values in Netlify dashboard)
# NEXT_PUBLIC_SUPABASE_URL = "your_supabase_url"
# NEXT_PUBLIC_SUPABASE_ANON_KEY = "your_supabase_anon_key"
# NEXT_PUBLIC_POSTHOG_KEY = "your_posthog_key"
# NEXT_PUBLIC_POSTHOG_HOST = "your_posthog_host"
# GOOGLE_AI_API_KEY = "your_google_ai_api_key"
# NEXTAUTH_URL = "https://your-site.netlify.app"
# NEXTAUTH_SECRET = "your_nextauth_secret"
