apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rigger-backend.fullname" . }}-config
  labels:
    {{- include "rigger-backend.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.configMap.data | nindent 2 }}
