apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rigger-backend.fullname" . }}-secrets
  labels:
    {{- include "rigger-backend.labels" . | nindent 4 }}
type: Opaque
data:
  DATABASE_URL: {{ include "rigger-backend.databaseUrl" . | b64enc }}
  REDIS_URL: {{ include "rigger-backend.redisUrl" . | b64enc }}
  JWT_SECRET: {{ .Values.secrets.jwt_secret | b64enc }}
  STRIPE_SECRET_KEY: {{ .Values.secrets.stripe_secret_key | b64enc }}
  STRIPE_WEBHOOK_SECRET: {{ .Values.secrets.stripe_webhook_secret | b64enc }}
  EMAIL_PASSWORD: {{ .Values.secrets.email_password | b64enc }}
  SUPABASE_URL: {{ .Values.secrets.supabase_url | b64enc }}
  SUPABASE_KEY: {{ .Values.secrets.supabase_key | b64enc }}
